# .github/workflows/deploy.yml
name: CI/CD Deploy and PR Test

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: echo "Building project..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to STAGING (development branch)
        if: github.ref == 'refs/heads/development'
        run: echo "Deploying to staging server..."

      - name: Deploy to PRODUCTION (master branch)
        if: github.ref == 'refs/heads/master'
        run: echo "Deploying to production server..."
